### ISSUE TITLE
Can't fill in all the required fields for CaptureOrderRequest while using paypal sandbox

### ISSUE THREAD

**Issue by archthegit** [plutov/paypal#175] opened 2020-10-08 02:34 UTC
Hi I am currently trying out this sdk before we decide to use it for our team, but I am unable to perform capture order correctly because fields like Billing Address and Security code in card information are not provided as part of the sandbox accounts. Can someone please help me unblock this ?

**Comment by roopakv** [comment] 2020-10-08 03:06
@archthegit which endpoint are you trying to use? we use this library in both sandbox and prod and has worked fine for us.

Would def love to get you unblocked.

**Comment by archthegit** [comment] 2020-10-08 03:13
`POST /v2/checkout/orders/ID/capture` this is the endpoint I am using. I call the CaptureOrder method like so :
` response, err := client.CaptureOrder(order.ID, captureOderReq)` But I am having issues with the CaptureOrderRequest object

**Comment by roopakv** [comment] 2020-10-08 03:44
@archthegit yeah this method is used in production by quite a few people using this library.

My guess is that you are hitting a weird edge case with their sandbox (we definitely ran into this). Happy to help debug, but I don't think this is an issue with the library itself.

If you need more help please post the actual issues you are seeing here :)

I am going to close out this request, feel free to respond, and I will help debug, but closing the issue out unless we can show that there is an issue with the lib itself.

**Closed as completed by roopakv** 2020-10-08 03:44 UTC

**Comment by archthegit** [comment] 2020-10-08 04:20
@roopakv I think the problem is with the fact that there is no cvv or billing address for the sandbox account although it is required by the CaptureOrderRequest object. I keep getting this error `{"name":"UNPROCESSABLE_ENTITY","details":[{"issue":"PAYEE_NOT_ENABLED_FOR_CARD_PROCESSING","description":"Payee account is not setup to be able to process card payments. Please contact PayPal customer support."}],"message":"The requested action could not be performed, semantically incorrect, or failed business validation.","debug_id":"99acb3a2e4fa1","links":[{"href":"https://developer.paypal.com/docs/api/orders/v2/#error-PAYEE_NOT_ENABLED_FOR_CARD_PROCESSING","rel":"information_link","method":"GET"}]}
`
I am not sure if this has something to do with the dummy cvv and billing address I put into the request object or if this is a paypal problem

**Comment by roopakv** [comment] 2020-10-08 05:45
are you taking payments for your own account, or on behalf of someone? if on behalf of someone you need to set your account up. my guess is that the problem is not related to CVV, but the dev account you have.

Usually payee errors mean that some sort of whitelisting is missing, or you do not have permissions to accept payments.
